// generated by hygen
import React from "react";
import styles from "./styles.module.scss"
import clsx from "clsx";

export const Main = React.forwardRef<
  HTMLDivElement,
  React.ComponentPropsWithoutRef<"div">
>(function MainBase({ className, ...props }, ref) {
  return (
    <div {...props} ref={ref} className={clsx(className, styles.module)} />
  );
});
