// generated by hygen
import { Meta, StoryObj } from "@storybook/react";
import { Main } from "./";

type T = typeof Main;
type Story = StoryObj<T>;

// ______________________________________________________
//

export default {
  component: Main
} as Meta<T>;

export const Default: Story = {};