// generated by hygen
import React from "react";
import { composeStories } from "@storybook/react";
import "@testing-library/jest-dom";
import { render } from "@testing-library/react";
import * as stories from "./Main.stories";

const { Default } = composeStories(stories);

describe("src/pages/Main", () => {

  test("pages である", () => {
    const { container } = render(<Default />);
    expect(container).toBePage();
  });

});
