// generated by hygen
import { Meta, StoryObj } from "@storybook/react";
import { Button } from "./";

type T = typeof Button;
type Story = StoryObj<T>;

// ______________________________________________________
//

export default {
  component: Button
} as Meta<T>;

export const Default: Story = {};