// generated by hygen
// import React from "react";
// import styles from "./styles.module.scss"
// import clsx from "clsx";

export const Button = () => {
  return (
    <button>test</button>
  )
 };
