// generated by hygen
import { composeStories } from '@storybook/react';
import "@testing-library/jest-dom";
import { render } from "@testing-library/react";
import * as stories from "./Button.stories";

const { Default } = composeStories(stories);

describe("src/components/organisms/Button", () => {

  test("organisms である", () => {
    const { container } = render(<Default />);
    expect(container)
  });

});
