---
to: <%= abs_path %>/<%= component_name %>.tsx
---
// generated by hygen
import React from "react";
import styles from "./styles.module.scss"
import clsx from "clsx";

export const <%= component_name %> = React.forwardRef<
  HTML<%= upperTag %>Element,
  React.ComponentPropsWithoutRef<"<%= tag %>">
>(function <%= component_name %>Base({ className, ...props }, ref) {
  return (
    <<%= tag %> {...props} ref={ref} className={clsx(className, styles.module)} />
  );
});
