---
to: <%= abs_path %>/<%= component_name %>.stories.tsx
---
// generated by hygen
import { Meta, StoryObj } from "@storybook/react";
import { <%= component_name %> } from "./";

type T = typeof <%= component_name %>;
type Story = StoryObj<T>;

// ______________________________________________________
//

export default {
  component: <%= component_name %>
} as Meta<T>;

export const Default: Story = {};